plugins:
- stylelint-scss
ignoreFiles:
- './build'
extends:
- stylelint-config-standard
- stylelint-config-standard-scss
rules:
  declaration-no-important: true
  selector-class-pattern: '^([A-Za-z]*(-|_|$))*'
  selector-id-pattern: '^([A-Za-z]*(-|$))*'